spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:medhead
    driver-class-name: org.h2.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
